In [9]:
import gym
import numpy as np
import random
import pixiedust


Pixiedust database opened successfully


In [3]:
env=gym.make("FrozenLake-v0")

In [4]:
action_size=env.action_space.n
state_size=env.observation_space.n

In [5]:
qtable=np.zeros((state_size,action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

In [13]:
#List of rewards
rewards=[]

# unitl learning is stopped
for episode in range(total_episodes):
    state=env.reset()
    step=0
    done=False
    total_rewards=0
    
    for step in range(max_steps):
        exp_exp_tradeoff=random.uniform(0,1)
        
        if exp_exp_tradeoff>epsilon:
            action=np.argmax(qtable[state,:])
        else:
            action=env.action_space.sample()
            
        new_state,reward,done,info=env.step(action)  
        
        
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards+=reward
        state=new_state
        if done==True:
            break
            
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)
    
print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.48346666666666666
[[2.73602585e-01 2.98162108e-02 2.81859292e-02 2.97266807e-02]
 [1.31184844e-02 7.39886208e-03 3.40981331e-03 6.56841669e-02]
 [6.85296919e-03 4.46990352e-03 9.20984352e-03 2.53343021e-02]
 [1.95600629e-03 8.53482214e-03 1.97541122e-03 1.57939361e-02]
 [2.84106149e-01 8.26972920e-03 2.78794171e-03 3.97586845e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.38368690e-05 1.69448729e-05 6.73833049e-02 3.90534169e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.77065498e-02 4.20842379e-03 3.88394817e-02 2.48226062e-01]
 [1.34093493e-02 2.55423499e-01 5.91859281e-02 1.35119418e-02]
 [1.05805205e-01 1.17742640e-03 3.30203946e-03 3.63241920e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.59303274e-02 1.42772000e-01 2.86492590e-01 6.16941879e-02]
 [1.98477748e-01 7.08058085e-01 2.05692053e-01 1.51612554e-01]
 [0.00000000e+00 0

In [15]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):
        
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        
        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 16
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 20
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 22
****************************************************
EPISODE  3
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 85


# Resources
* https://medium.freecodecamp.org/diving-deeper-into-reinforcement-learning-with-q-learning-c18d0db58efe